### ISSUE TITLE
Primary Key query performance

### ISSUE THREAD

**Issue by EvgeniyZviryaka** [zzzprojects/nmemory#37] opened 2018-12-21 14:21 UTC
Hi All,
Thanks for all the efforts. Great library.

I have a question about the expected performance in a scenario involving primary key.
I've used your example with the following changes: 
```
  class Program
  {
        static void Main(string[] args)
        {
            var db = new MyDatabase();
            db.People.Insert(new Person
            {
                Id = 1,
                Name = "John Doe"
            });
            var query = db.People.Where(x => x.Id == 1);
            var plan = db.DatabaseEngine.Compiler.Compile<IEnumerable<Person>>(query.Expression);
            Console.WriteLine(plan.Info.Final);
        }
    }
```
Console output is `Table<Person>.SelectAll().Where(x => (x.Id == 1))`
If I undersdand correctly from this output, get by ID use full scan execution plan and don't use primary key index. 
Is it expected behavior?

**Comment by JonathanMagnan** [comment] 2018-12-24 16:31
Hello @EvgeniyZviryaka ,

Thank you for reporting, we will try to investigate it this week.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by EvgeniyZviryaka** [comment] 2019-01-09 13:16
Hello @JonathanMagnan, 
Do you have any updates regarding my question?

**Comment by JonathanMagnan** [comment] 2019-01-10 02:40
Hello @EvgeniyZviryaka ,

We have investigated it and you are right.

All entities from the indexes are returned and it's the LINQ `Where` logic that solves the predicate. So the primary key index is somewhat never used in this scenario.

That's probably an expected behavior since the library doesn't translate LINQ expression.

What's probably missing is a `Find` method that will directly take the entity from the primary key index. Looking at the code, pretty much everything is here to support it.

It's a solution that could work for you?

Best Regards,

Jonathan

**Comment by EvgeniyZviryaka** [comment] 2019-01-14 09:02
Hello @JonathanMagnan,
Unfortunately no, I thought that this library can automatically use indexes based on LINQ expression. 
I need in-memory query engine that can filter 300 000 items based on their properties (id, status, startDate and etc.)

**Comment by JonathanMagnan** [comment] 2019-01-14 13:47
Unfortunately, I don't think `NMemory` will do the job ;(

This request might be too complex and too long to implement it at this moment.

**Comment by JonathanMagnan** [comment] 2019-01-20 20:11
Hello @EvgeniyZviryaka ,

We will close this request but it will stay open on our internal `ChangeTracker`.

As said, we have no short-term plan to implement something like this.

Best Regards,

Jonathan

**Closed as completed by JonathanMagnan** 2019-01-20 20:11 UTC
