### ISSUE TITLE
Order by multiple crtiterias

### ISSUE THREAD

**Issue by StephaneG31** [zzzprojects/nmemory#28] opened 2018-08-23 19:42 UTC
We just use Effort to test our EF querys. We use ordering with multiple criterias but it's seems Effort base on nmemory cannot sort by multiple crtiterias (ThenBy...ThenBy)
Do you confirm this limitation ?

**Comment by JonathanMagnan** [comment] 2018-08-24 03:19
Hello @StephaneG31 ,

Thank you for reporting,

We shipped this week a new version of `NMemory` (Used by Effort) to support Order clause.

We will look at this issue and check if that's already fixed in the new version.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment] 2018-08-28 17:42
Hello @StephaneG31 ,

My developer made some test and everything looks to work fine.

```csharp
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Common;
using System.Data.Entity;
using System.Linq;

namespace Effort.Lab.EF6
{
    public class Request_OrderBy
    {
        public static void Execute()
        {
            var connection = DbConnectionFactory.CreateTransient();

            using (var context = new EntitiesContext(connection))
            {
                for (var i = 0; i < 10; i++)
                {
                    var test = new MyEntity {ColumnText = (i % 3).ToString(), ColumnChar = i.ToString()};

                    context.MyEntities.Add(test);
                }

                context.SaveChanges();
            }

            using (var context = new EntitiesContext(connection))
            {
                var list = context.MyEntities.OrderByDescending(x => x.ColumnText).ThenByDescending(y => y.ColumnChar).ToList();
            }
        }
    }

    public class EntitiesContext : DbContext
    {
        public EntitiesContext(DbConnection dbConnection) : base(dbConnection, true)
        {
        }

        public virtual DbSet<MyEntity> MyEntities { get; set; }
    }

    public class MyEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public string ColumnText { get; set; }

        public string ColumnChar { get; set; }
    }
}
```

Are we missing something?

Could you provide a sample project with this issue?

Best Regards,

Jonathan

**Comment by StephaneG31** [comment] 2018-08-28 18:01
Hi @JonathanMagnan,
Thanks for your fast reply.
We encounter this problem with Effort.EF6 in a context where we load data from a csv file.
First order is asc, the second one is desc.
We made a UnitTest : we grab the list order by A asc then B desc by EF (so throw Effort). Then we order again this list by the same criteria on local by Linq, then assert is the list is ordered in the same order by FluentAssertions.

In the next days, we will try to extract our datas to a simple test/project to show if we can reproduce this in other context than our project.

**Comment by JonathanMagnan** [comment] 2018-08-28 18:19
Great, we will wait for your project if you success to reproduce it.

**Comment by JonathanMagnan** [comment] 2018-09-09 21:46
Hello @Jon,

This issue will be closed since we haven't heard back from you.

If you can provide the project, we will be happy to re-open this issue and look at it.

Best Regards,

Jonathan

**Closed as completed by JonathanMagnan** 2018-09-09 21:46 UTC
